# Generated by Django 5.1.7 on 2025-06-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='precio',
            new_name='precio_uni',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='paquete',
            name='fecha_regreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='fecha_vuelo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
